- name: Send consolidated VM report
  hosts: localhost
  gather_facts: true
  vars:
    collected_metrics: "{{ all_vm_metrics | default([]) }}"
    timestamp: "{{ ansible_facts['date_time'].date }} {{ ansible_facts['date_time'].time }}"
    subject_line: "📊 VM Report – {{ ansible_facts['date_time'].date }} {{ ansible_facts['date_time'].hour }}:{{ ansible_facts['date_time'].minute }}"
  tasks:
    - name: Abort if no metrics were collected
      fail:
        msg: "No VM metrics collected. Skipping email report."
      when: collected_metrics | length == 0

    - name: Send HTML VM report via Gmail
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ email_user }}"
        password: "{{ email_pass }}"
        to: "{{ alert_recipient }}"
        subject: "{{ subject_line }}"
        body: "{{ lookup('template', 'templates/report_email_animated.html.j2') }}"
        subtype: html
        secure: starttls
